link:https://www.kaggle.com/datasets/matheusfreitag/gas-prices-in-brazil/data

In [107]:
import pandas as pd

In [108]:
#carregando dados
df= pd.read_csv("./2004-2021.tsv", sep= "\t")
df.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

In [109]:
#Alterando o tipo dos dados
df["DATA FINAL"] = pd.to_datetime(df["DATA FINAL"])
df["DATA INICIAL"]= pd.to_datetime(df["DATA INICIAL"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(1), object(10)
memory usage: 16.6+ MB

In [110]:
#Alterando os atributos para numéricos
for atributo in['MARGEM MÉDIA REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'] :
    df[atributo] = pd.to_numeric(df[atributo], errors= "coerce")
    df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           117392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[ns](2), float64(6), int64(1), object(9)
memory usage: 16.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           117392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       117423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(1), object(8)
memory usage: 16.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           117392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       117423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     117423 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[ns](2), float64(8), int64(1), object(7)
memory usage: 16.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           117392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       117423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     117423 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      117423 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[ns](2), float64(9), int64(1), object(6)
memory usage: 16.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           117392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       117423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     117423 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      117423 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      117423 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  object
dtypes: datetime64[ns](2), float64(10), int64(1), object(5)
memory usage: 16.6+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           117392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       117423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     117423 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      117423 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      117423 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  117423 non-null  float64
dtypes: datetime64[ns](2), float64(11), int64(1), object(4)
memory usage: 16.6+ MB

In [111]:
#consultando dados sem salvar nenhuma variavel
df.query('REGIÃO in["CENTRO OESTE", "SUL", "NORDESTE"]')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120813,2021-04-25,2021-05-01,NORDESTE,PIAUI,OLEO DIESEL S10,36,R$/l,4.382,0.172,3.999,4.897,-99999.000,0.039,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120815,2021-04-25,2021-05-01,NORDESTE,RIO GRANDE DO NORTE,OLEO DIESEL S10,24,R$/l,4.699,0.101,4.490,4.890,-99999.000,0.021,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120816,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL S10,148,R$/l,4.140,0.236,3.849,4.949,-99999.000,0.057,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.000,0.045,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.000,0.046,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000

In [112]:
#filtrando por regiões
selec_1 = df["REGIÃO"] == "SUL"
selec_2 = df["REGIÃO"] == "CENTRO OESTE"

df_selec_regiao = selec_1 | selec_2
df[df_selec_regiao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143
24,2004-05-09,2004-05-15,SUL,PARANA,ETANOL HIDRATADO,760,R$/l,0.922,0.083,0.740,1.500,0.255,0.090,0.667,0.105,0.4357,0.95870,0.157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120806,2021-04-25,2021-05-01,CENTRO OESTE,MATO GROSSO,OLEO DIESEL S10,101,R$/l,4.594,0.139,4.299,4.899,-99999.000,0.030,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120807,2021-04-25,2021-05-01,CENTRO OESTE,MATO GROSSO DO SUL,OLEO DIESEL S10,44,R$/l,4.232,0.151,3.990,4.699,-99999.000,0.036,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120811,2021-04-25,2021-05-01,SUL,PARANA,OLEO DIESEL S10,142,R$/l,4.044,0.166,3.739,4.590,-99999.000,0.041,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120816,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL S10,148,R$/l,4.140,0.236,3.849,4.949,-99999.000,0.057,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.000,0.045,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000

In [113]:
#verificando valores nulos
df["PREÇO MÁXIMO DISTRIBUIÇÃO"].isnull().sum()

np.int64(3400)

In [114]:
#removendo dados nulos na tabela teste
df_teste= df.dropna()
df_teste

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.000,0.012,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.000,0.045,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.000,0.051,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.000,0.046,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.000,0.036,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000

In [115]:
#retorna os valores nulos
df_nulos = df[df.isnull().any(axis=1)]
df_nulos

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,2.090,NaN,0.167,NaN,NaN,NaN,NaN,NaN
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,2.000,NaN,0.000,NaN,NaN,NaN,NaN,NaN
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,2.290,NaN,0.010,NaN,NaN,NaN,NaN,NaN
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,2.200,NaN,0.018,NaN,NaN,NaN,NaN,NaN
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,2.300,NaN,0.030,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,3.699,NaN,0.043,NaN,NaN,NaN,NaN,NaN
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,3.890,NaN,0.094,NaN,NaN,NaN,NaN,NaN
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,3.299,NaN,0.002,NaN,NaN,NaN,NaN,NaN
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,3.699,NaN,0.028,NaN,NaN,NaN,NaN,NaN
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,3.290,NaN,0.000,NaN,NaN,NaN,NaN,NaN

In [116]:
#Retorna a linhas sem os valores nulos
df_teste_1 = df.dropna(axis=0)
df_teste_1

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.000,0.012,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.000,0.045,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.000,0.051,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.000,0.046,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.000,0.036,-99999.000,-99999.000,-99999.0000,-99999.00000,-99999.000

In [117]:
#Retorna as colunas sem os valores nulos
df_teste_2 = df.dropna(axis=1)
df_teste_2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,COEF DE VARIAÇÃO REVENDA
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.012
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.098
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.070
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.055
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.066
...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,0.012
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,0.045
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,0.051
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,0.046
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,0.036

In [131]:
#media dos valores
df_teste_4 = df.fillna(df.mean(numeric_only=True))
df_teste_4.mean(numeric_only=True)

NÚMERO DE POSTOS PESQUISADOS      221.066461
PREÇO MÉDIO REVENDA                11.473440
DESVIO PADRÃO REVENDA               0.684132
PREÇO MÍNIMO REVENDA                9.977821
PREÇO MÁXIMO REVENDA               13.233902
MARGEM MÉDIA REVENDA            -4697.376395
COEF DE VARIAÇÃO REVENDA            0.045298
PREÇO MÉDIO DISTRIBUIÇÃO        -4682.188208
DESVIO PADRÃO DISTRIBUIÇÃO      -4690.133173
PREÇO MÍNIMO DISTRIBUIÇÃO       -4683.305792
PREÇO MÁXIMO DISTRIBUIÇÃO       -4680.965828
COEF DE VARIAÇÃO DISTRIBUIÇÃO   -4690.642465
dtype: float64

In [120]:
#localizando valores nulos
df_nulos = df["PREÇO MÉDIO DISTRIBUIÇÃO"].isnull()
df[df_nulos]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,2.090,NaN,0.167,NaN,NaN,NaN,NaN,NaN
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,2.000,NaN,0.000,NaN,NaN,NaN,NaN,NaN
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,2.290,NaN,0.010,NaN,NaN,NaN,NaN,NaN
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,2.200,NaN,0.018,NaN,NaN,NaN,NaN,NaN
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,2.300,NaN,0.030,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,3.699,NaN,0.043,NaN,NaN,NaN,NaN,NaN
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,3.890,NaN,0.094,NaN,NaN,NaN,NaN,NaN
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,3.299,NaN,0.002,NaN,NaN,NaN,NaN,NaN
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,3.699,NaN,0.028,NaN,NaN,NaN,NaN,NaN
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,3.290,NaN,0.000,NaN,NaN,NaN,NaN,NaN

In [132]:
df_teste_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object
 3   ESTADO                         120823 non-null  object
 4   PRODUTO                        120823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  object
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  float64
dtypes: datetime64[ns](2), float64(11), int64(1), object(4)
memory usage: 16.6+ MB

In [ ]:
df_teste_4 = df_teste_1

In [ ]:
#Renomeando colunas
column_mapping = {
    "REGIÃO": "Região",
    "ESTADO": "Estado",
    "PRODUTO": "Produto",
    "UNIDADE DE MEDIDA": "Unidade de Medida",
    "MARGEM MÉDIA REVENDA": "Margem Média Revenda",
    "PREÇO MÉDIO DISTRIBUIÇÃO": "Preço Médio Distribuição",
    "DESVIO PADRÃO DISTRIBUIÇÃO": "Desvio Padrão Distribuição",
    "PREÇO MÍNIMO DISTRIBUIÇÃO": "Preço Mínimo Distribuição",
    "PREÇO MÁXIMO DISTRIBUIÇÃO": "Preço Máximo Distribuição",
    "COEF DE VARIAÇÃO DISTRIBUIÇÃO": "Coef de Variação Distribuição",
    "DATA INICIAL": "Data Inicial",
    "DATA FINAL": "Data Final"

}
df_teste_4 = df_teste_4.rename(columns=column_mapping)

In [ ]:
#Renomeando mais colunas
column_mapping={
    "NÚMERO DE POSTOS PESQUISADOS": "Número de Postos",
    "PREÇO MÉDIO REVENDA": "Preço Médio Revenda",
    "DESVIO PADRÃO REVENDA": "Desvio Padrão Revenda",
    "PREÇO MÍNIMO REVENDA": "Preço Mínimo Revenda",
    "PREÇO MÁXIMO REVENDA": "Preço Máximo Revenda",
    "COEF DE VARIAÇÃO REVENDA": "Coef de Variação Revenda"
    }
df_teste_4.rename(columns=column_mapping, inplace=True)

In [146]:
#limpando valores inválidos
df_teste_4 = df_teste_4[df_teste_4["Margem Média Revenda"] > -99]

In [148]:
df_teste_4

,Data Inicial,Data Final,Região,Estado,Produto,Número de Postos,Unidade de Medida,Preço Médio Revenda,Desvio Padrão Revenda,Preço Mínimo Revenda,Preço Máximo Revenda,Margem Média Revenda,Coef de Variação Revenda,Preço Médio Distribuição,Desvio Padrão Distribuição,Preço Mínimo Distribuição,Preço Máximo Distribuição,Coef de Variação Distribuição
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115879,2020-08-16,2020-08-22,NORTE,RORAIMA,OLEO DIESEL S10,13,R$/l,3.459,0.123,3.180,3.590,0.350,0.036,3.109,0.104,2.9400,3.27940,0.033
115880,2020-08-16,2020-08-22,SUL,SANTA CATARINA,OLEO DIESEL S10,236,R$/l,3.395,0.190,3.060,3.999,0.448,0.056,2.947,0.093,2.8500,3.09980,0.032
115881,2020-08-16,2020-08-22,SUDESTE,SAO PAULO,OLEO DIESEL S10,1267,R$/l,3.386,0.197,2.979,4.699,0.413,0.058,2.973,0.108,2.3080,3.27000,0.036
115882,2020-08-16,2020-08-22,NORDESTE,SERGIPE,OLEO DIESEL S10,39,R$/l,3.559,0.183,3.340,3.799,0.513,0.051,3.046,0.061,2.9700,3.11040,0.020
115883,2020-08-16,2020-08-22,NORTE,TOCANTINS,OLEO DIESEL S10,45,R$/l,3.458,0.277,3.139,5.070,0.406,0.080,3.052,0.065,3.0135,3.18080,0.021

In [128]:
#localizando uma linha específica
df_teste_4.loc[8]

DATA INICIAL                     2004-05-09 00:00:00
DATA FINAL                       2004-05-15 00:00:00
REGIÃO                                      NORDESTE
ESTADO                                       PARAIBA
PRODUTO                             ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                     125
UNIDADE DE MEDIDA                               R$/l
PREÇO MÉDIO REVENDA                            1.284
DESVIO PADRÃO REVENDA                           0.13
PREÇO MÍNIMO REVENDA                             1.1
PREÇO MÁXIMO REVENDA                           1.699
MARGEM MÉDIA REVENDA                           0.353
COEF DE VARIAÇÃO REVENDA                       0.101
PREÇO MÉDIO DISTRIBUIÇÃO                       0.931
DESVIO PADRÃO DISTRIBUIÇÃO                     0.072
PREÇO MÍNIMO DISTRIBUIÇÃO                     0.7577
PREÇO MÁXIMO DISTRIBUIÇÃO                     1.2972
COEF DE VARIAÇÃO DISTRIBUIÇÃO                  0.077
Name: 8, dtype: object

In [149]:
df_teste_4.to_csv("baseFiltrada2.csv", sep=";")